name: Build source

on: [ workflow_dispatch ]

# 環境にあわせて修正してください。
env:
  # ソースファイルのあるフォルダ
  SOURCE_FOLDER: src/GrandChildLib

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Chackout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Add Source
      run: dotnet nuget add source "https://nuget.pkg.github.com/maegawa-h/index.json" -n github -u ${{ secrets.NUGET_GITHUB_USER }} -p ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.SOURCE_FOLDER}}

    - name: Build
      run: dotnet build ${{env.SOURCE_FOLDER}} --no-restore

