name: update-csproj-version

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Chackout Code
      uses: actions/checkout@v2

    - name: Check Release View
      uses: Hedgehogs0808/UpdateCsprojectVersion@main
      with:
        github-token: test
        target-dir: .\src
